### ISSUE TITLE
Where can I find the dataset?

### ISSUE THREAD

**Issue by Rajat-Mehta** [AbhishekPrasanth/GPR_Detection#1]
Can I get access to the dataset that you have used in your work?

**Comment by AbhishekPrasanth** [comment]
hi,
you can either find it in my git itself or refer this link
http://github.com/PouriaAI/GPR-Detection/

**Comment by Rajat-Mehta** [comment]
Thanks for your response Abhishek. 

In your guide you have mentioned that you used GPR images, but the link that you provided is for a ".7z" file format. Can you please clarify this confusion?

**Comment by AbhishekPrasanth** [comment]
hi,
download the file and extract the file.inside the folder test and train
there will be images.
